test:
	javac -cp .:hamcrest-core-1.3.jar:junit.jar *.java
	java -cp .:hamcrest-core-1.3.jar:junit.jar SearchTests
keytest:
	javac -cp .:hamcrest-core-1.3.jar:junit.jar *.java
	java -cp .:hamcrest-core-1.3.jar:junit.jar KeywordTests
run:
	javac -cp .:hamcrest-core-1.3.jar:junit.jar *.java
	java Driver
